require("thameera.plugins-setup")

require("thameera.core.options")
require("thameera.core.keymaps")
require("thameera.core.colorscheme")

require("thameera.plugins.interestingwords")
require("thameera.plugins.comment")
require("thameera.plugins.nvim-tree")
require("thameera.plugins.lualine")
require("thameera.plugins.telescope")
require("thameera.plugins.nvim-cmp")
require("thameera.plugins.autopairs")
require("thameera.plugins.treesitter")
require("thameera.plugins.rust-tools")
require("thameera.plugins.go")

require("thameera.plugins.lsp.mason")
require("thameera.plugins.lsp.lspsaga")
require("thameera.plugins.lsp.lspconfig")
